import React, { useState,useEffect } from 'react';
import AddCard from './src/components/AddCard';
import { Dimensions,ScrollView} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createNativeStackNavigator} from '@react-navigation/native-stack';
import TrackList from './src/components/TrackList';
import { LogBox } from 'react-native';
import BackgroundTask from 'react-native-background-task'
import { Notifications } from "react-native-notifications";

const Stack = createNativeStackNavigator();
BackgroundTask.define(() => {
  console.log('Hello from a background task');
  Notifications.postLocalNotification({
    title: "Local notification",
    body: "This notification was generated by the app!",
    extra: "data"
  });
  BackgroundTask.finish()
})

const App= () =>  {
  const[Items,setItems] = useState([]);
  useEffect(() => {
    LogBox.ignoreLogs(['VirtualizedLists should never be nested']);
    BackgroundTask.schedule({
      period: 900, // Aim to run every 30 mins - more conservative on battery
    })
}, [])
  

  const AddData =(data)=>{
    let newarray = [...Items,data]
    setItems(newarray);
  }
  const deleteItem =(data)=>{
    let newarray = Items.filter(item => item.title !== data);
    setItems(newarray);
  }

  let ScreenHeight = Dimensions.get("window").height;
  return (
   <NavigationContainer>
    <Stack.Navigator screenOptions={{headerShown: false}}>
    <Stack.Screen name="Home">
      {(props)=><AddCard {...props} addData={AddData}></AddCard>}
    </Stack.Screen>
    <Stack.Screen name="List" >
      {(props)=><TrackList {...props} deleteItem={deleteItem} items={Items}></TrackList>}
    </Stack.Screen>
    </Stack.Navigator>
  </NavigationContainer>
  )

}

export default App;
/*  <NavigationContainer>
    <Stack.Navigator>
    <Stack.Screen
          name="Home"
          component={TrackList}
          options={{title: 'Welcome'}}
        />
    </Stack.Navigator>
  </NavigationContainer>
<ScrollView style={{backgroundColor:"white", height:ScreenHeight}}>
          <AddCard addData={AddData}></AddCard>
          <TrackList deleteItem={deleteItem} items={Items}></TrackList>
        </ScrollView>*/