import React from "react";
import { useState } from 'react';
import { TextInput,View,Linking,Switch, Image,Text,TouchableOpacity,ActivityIndicator,  Alert  } from "react-native";
import styles from "../css/addCardCss";
import fetchData from '../requestHandler/fetchhandler';
import Icon from 'react-native-vector-icons/FontAwesome5';
import Notification from "../notification/notification";
import { Notifications } from "react-native-notifications";
const AddCard = ({navigation, ...props})=>{
    const [inputUrl, setInputUrl] = useState('');
    const [fetchedData, setData] = useState('');
    const [imgSrc, setimgSrc] = useState('');
    const [title, setTitle] = useState('');
    const [loadingAnimation,setloadingAnimation] = useState(false);
    const [showResults,setShowResults] = useState(false);

    const onButtonClick =async ()=>{
      
        setloadingAnimation(true);
        let resultProduct = await fetchData(inputUrl);
        
        setData(resultProduct.price);
        setimgSrc(resultProduct.imageSrc);
        setTitle(resultProduct.title);
        setloadingAnimation(false);
        setShowResults(true);
        
      }

    const onPressCross =()=>{
      Notifications.postLocalNotification({
        title: "Local notification",
        body: "This notification was generated by the app!",
        extra: "data"
    });
      setShowResults(false);
      setInputUrl('');
    }
    const addToTracker=()=>{
      props.addData({title:title,price:fetchedData,imgSrc:imgSrc});
      navigation.navigate('List');
    }
    const visitProduct=()=>{
        Linking.openURL(inputUrl);
    }

    return(
    <View className="addCard">
      <View style={{flexDirection:'row'}}>
        <TouchableOpacity  onPress={onPressCross} style={styles.crossButton}>
            
            </TouchableOpacity>
        <Text >{'Track Product'}</Text>
        
      </View>
      { !showResults&& 
        <View className="fetchBox">
          <TextInput style={styles.textInput} placeholder="Paste the link" placeholderTextColor={"black"} value={inputUrl} onChangeText={setInputUrl} />
          <View style={{alignItems:"center"}}>
            <TouchableOpacity  onPress={onButtonClick} style={styles.button} >
              { !loadingAnimation && <Text style={{color:"white"}}>{"Track1"}</Text>}
              { loadingAnimation&& <ActivityIndicator animating={loadingAnimation}/>}
            </TouchableOpacity>
          </View>
        </View> }
      {showResults &&
        <View className="resultBox">
            <View style={styles.imageBox}>
              <Image source={{uri:imgSrc}} resizeMode={"contain"} style={styles.image} />
            </View>
          <Text style={styles.title}>{title}</Text>
          <Text style={{color:"#7c038c",marginLeft:10}}>{'Current Price'}</Text>
          <Text style={styles.price}>{fetchedData}</Text>
          <View style={{flexDirection:"row"}}>
          <Switch value={true}></Switch>
          <Text style={{color:"black",marginLeft:10}}>{"Notify on Every Price Change"}</Text>
          </View>
          
        </View> 
      }
      {showResults && 
            <View style={{flexDirection:"row",marginLeft:10}}>
            <TouchableOpacity style={styles.storeButton} onPress={visitProduct}>
                <Icon name='store' size={20} style={{marginRight:12,marginLeft:6,color:"#fff200"}}></Icon>
                <Text style={{fontSize:17,fontWeight:"bold",color:"white"}}>{'Flipkart'}</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={addToTracker} style={styles.trackerButton}>
              <Text style={{fontSize:17,fontWeight:"bold",color:"white"}}>{"Add To Tracker"}</Text>
            </TouchableOpacity> 
            
          </View>}

    </View>
    )
}

export default AddCard;